### ISSUE TITLE
Division by zero errors

### ISSUE THREAD

**Issue by eunhwanshin** [tbrown122387/pf#14]
I tried to build "pf" in VisualStudio and met "division by zero" errors due to the following line:
float_t maxOldLogUnNormWts(-1.0/0.0);
which can be found in bootstrap_filter.h and sisr_filter.h.

**Comment by tbrown122387** [comment]
Thanks @eunhwanshin nice spot! Now fixed by [this commit](https://github.com/tbrown122387/pf/commit/d491ee30e075ba34b72bbafe3082ba0798c1498c) and [this one](https://github.com/tbrown122387/pf/commit/239f2086587e91d625da5be620de257bb37e6c45)
