### ISSUE TITLE
[question] Where and what is the "example related to tracking" mentionned in the ideas List

### ISSUE THREAD

**Issue by iad-ABDUL-RAOUF** [tbrown122387/pf#28]
Hi ! first of all, thank you for the work put in developing this repository.

In the Ideas List it is mentioned that : "... there is another example related to tracking ...".
1. However, in the "examples" directory I can't find this tracking example. They are all about stochastic volatility. Am I missing something?
2. Also what is the state-space model used in this tracking example ? (state dynamic and observation model)

Thanks !

(btw it seems i can't add a label to the issue myself, therefore i added it in the title)

**Comment by tbrown122387** [comment]
The other example is in [smctc_comparison_example/](https://github.com/tbrown122387/pf/tree/master/smctc_comparison_example) The primary purpose of this example was to compare the speed of two different implementations of the same model. To keep them on an equal footing, I took the model described in the CMCTC paper: file:///home/trb5me_admin/Desktop/csct_subs/Python/WRAP_johansen_paper.pdf

**Comment by tbrown122387** [comment]
@iad-ABDUL-RAOUF does that answer your question? If so, do you mind if I close this issue?

**Comment by iad-ABDUL-RAOUF** [comment]
thanks a lot ! yes it does. You can close the issue
